server:
  port: 80
  context-path: /casServer
spring:
   freemarker:
     settings:
        number_format: 0.###
        boolean_format: true,false
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss
     cache: false
     checkTemplateLocation: true
     contentType: text/html
     suffix: .html
     request-context-attribute: request
     templateEncoding: UTF-8
     templateLoaderPath: classpath:/templates/
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.56.101:3306/test?useUnicode=true&characterEncoding=utf8
       username: root
       password: RZ1655362684
   jpa:
       show-sql: true
   redis:
       host: 192.168.56.101
       password:
       port: 6381
       pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -1
#配置数据库
database: user_entity
#填写需要返回给客户端的用户数据库的列名,如果不配置，默认返回所有列的值
#key:域名.sqlcolumn-name value：对应数据库列名 比如：localhost.sqlcolumn-name: id,name
#app1.rz.com.sqlcolumn-name: *
# 填写自己网站自定义的登录界面,如果不配置，默认进入系统提供的登录页面
#key:域名.login-page-name value：文件名字 比如：localhost.login-page-name: login
#app1.rz.com.login-page-name: login